#!/usr/bin/env python3
"""Set up the Vue3 frontend for e2e testing against the local Rust backend.

Creates `.env.development.local` in the Vue project to override the Vite proxy
target, pointing `/api` at the local Rust backend instead of the remote dev
server. Also runs `pnpm install` if node_modules is missing or incomplete.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

# Add parent for imports
sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import RUST_PORT, VUE_FRONTEND  # noqa: E402


def ensure_env_override() -> None:
    """Create .env.development.local to proxy /api → local Rust backend."""
    env_local = VUE_FRONTEND / ".env.development.local"
    content = f"""\
# Auto-generated by e2e/setup_frontend.py — do not commit.
# Points the Vite dev proxy at the local Rust backend.
VITE_API_BASE=/api
VITE_API_PROXY_TARGET=http://127.0.0.1:{RUST_PORT}
VITE_WS_BASE=ws://127.0.0.1:{RUST_PORT}/ws
"""
    env_local.write_text(content, encoding="utf-8")
    print(f"✅ Wrote {env_local}")

    # Ensure .gitignore has the entry
    gitignore = VUE_FRONTEND / ".gitignore"
    if gitignore.exists():
        lines = gitignore.read_text(encoding="utf-8").splitlines()
        if ".env.*.local" not in lines and ".env.development.local" not in lines:
            with open(gitignore, "a", encoding="utf-8") as fh:
                fh.write("\n# e2e local override\n.env.*.local\n")
            print(f"✅ Added .env.*.local to {gitignore}")


def ensure_deps() -> None:
    """Run pnpm install if node_modules is missing or incomplete."""
    node_modules = VUE_FRONTEND / "node_modules"
    if node_modules.exists() and any(node_modules.iterdir()):
        count = sum(1 for _ in node_modules.iterdir())
        if count > 100:
            print(f"✅ node_modules has {count} entries — skipping install")
            return

    print("📦 Running pnpm install...")
    result = subprocess.run(
        ["pnpm", "install"],
        cwd=str(VUE_FRONTEND),
        shell=True,
        capture_output=True,
        text=True,
        timeout=300,
    )
    if result.returncode != 0:
        print(f"❌ pnpm install failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    print("✅ pnpm install complete")


def main() -> int:
    if not VUE_FRONTEND.exists():
        print(f"❌ Vue frontend not found at {VUE_FRONTEND}", file=sys.stderr)
        return 1

    ensure_env_override()
    ensure_deps()
    print("\n✨ Frontend ready for e2e testing.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
