#!/usr/bin/env python3
"""Set up the Vue3 frontend for e2e testing against the local Rust backend.

Creates `.env.development.local` to override the Vite proxy → local Rust backend.
Runs `pnpm install` if node_modules is missing.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import RUST_PORT, VUE_FRONTEND  # noqa: E402
from log import info, warn, error  # noqa: E402

TARGET = "e2e::setup"


def ensure_env_override() -> None:
    env_local = VUE_FRONTEND / ".env.development.local"
    content = f"""\
# Auto-generated by e2e/setup_frontend.py — do not commit.
VITE_API_BASE=/api
VITE_API_PROXY_TARGET=http://127.0.0.1:{RUST_PORT}
VITE_WS_BASE=ws://127.0.0.1:{RUST_PORT}/ws
# Map tiles/icons are GB-scale: they must come straight from the CDN (the
# production contract), NOT through the local backend proxy — proxying
# hundreds of concurrent tile requests through the dev backend stalls the
# map. assets.yuanshen.site sends Access-Control-Allow-Origin: *.
VITE_ASSETS_BASE=https://assets.yuanshen.site
# The dadian config is small (tens of KB); serve it from the local backend
# (CDN_DADIAN_CONFIG) so the tiles/area definitions are pinned to the
# version this backend was tested with.
VITE_CONFIG_ARCHIVE=http://127.0.0.1:{RUST_PORT}/cdn/dadian-preview.json.bz2
"""
    env_local.write_text(content, encoding="utf-8")
    info(TARGET, f"Wrote {env_local}")

    gitignore = VUE_FRONTEND / ".gitignore"
    if gitignore.exists():
        lines = gitignore.read_text(encoding="utf-8").splitlines()
        if ".env.*.local" not in lines:
            with open(gitignore, "a", encoding="utf-8") as fh:
                fh.write("\n# e2e local override\n.env.*.local\n")
            info(TARGET, "Added .env.*.local to .gitignore")


def ensure_deps() -> bool:
    node_modules = VUE_FRONTEND / "node_modules"
    if node_modules.exists() and any(node_modules.iterdir()):
        count = sum(1 for _ in node_modules.iterdir())
        if count > 10:
            info(TARGET, f"node_modules ready ({count} entries)")
            return True

    info(TARGET, "Running pnpm install...")
    # Resolve pnpm to an absolute path (pnpm.cmd on Windows) so the child runs
    # as a plain argv list without going through the shell.
    pnpm = shutil.which("pnpm")
    if not pnpm:
        error(TARGET, "pnpm not found on PATH — cannot install frontend deps")
        return False
    result = subprocess.run(
        [pnpm, "install"],
        cwd=str(VUE_FRONTEND),
        capture_output=True,
        text=True,
        timeout=300,
    )
    if result.returncode != 0:
        error(TARGET, f"pnpm install failed:\n{result.stderr}")
        return False
    info(TARGET, "pnpm install complete")
    return True


def main() -> int:
    if not VUE_FRONTEND.exists():
        error(TARGET, f"Vue frontend not found at {VUE_FRONTEND}")
        return 1

    ensure_env_override()
    if not ensure_deps():
        warn(TARGET, "Frontend deps not ready, continuing anyway.")
    else:
        info(TARGET, "Frontend ready.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
