# Attention: This cluster configuration is **not** for production use!
# 注意：该集群配置**不是**生产环境配置！

services:
  postgres:
    image: postgres:latest
    container_name: test-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: genshin_map
      POSTGRES_PASSWORD: genshin_map
      POSTGRES_DB: genshin_map
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: test-redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PORT: 6379
    volumes:
      - redis-data:/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: test-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: genshin_cloud
      MINIO_ROOT_PASSWORD: genshin_cloud
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

  # alist:
  #   image: xhofe/alist:latest
  #   container_name: test-alist
  #   ports:
  #     - "5244:5244"
  #   volumes:
  #     - alist-data:/data
  #   restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
  minio-data:
  # alist-data:
