# 请注意，该集群配置**不是**生产环境配置，只用于本地测试环境

services:
  redis:
    image: redis:latest
    container_name: test-redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PORT: 6379
    volumes:
      - redis-data:/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: test-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: genshin_cloud
      MINIO_ROOT_PASSWORD: genshin_cloud
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

  # alist:
  #   image: xhofe/alist:latest
  #   container_name: test-alist
  #   ports:
  #     - "5244:5244"
  #   volumes:
  #     - alist-data:/data
  #   restart: unless-stopped

volumes:
  redis-data:
  minio-data:
  # alist-data:
