[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
script = '''
#!@duckscript

exec docker build -t kongying-tavern-backend .
'''

[tasks.dev]
env_files = ["./.env"]
watch = { no_git_ignore = true, ignore_pattern = "Cargo.lock", watch = [
  "./packages/",
] }
script = '''
#!@duckscript

exec docker compose -f dev.compose.yml up -d
exec cargo run
'''

[tasks.dev.env]
DB_HOST = "127.0.0.1"
DB_PORT = "5432"
DB_USERNAME = "genshin_map"
DB_DATABASE = "genshin_map"

MINIO_ACCESS_KEY = "genshin_cloud"
MINIO_SECRET_KEY = "genshin_cloud"

[tasks.clean]
script = '''
#!@duckscript

exec cargo clean
exec docker compose -f dev.compose.yml down
'''
